/* tests/filtering/test_amiga_endian.c - Amiga endianness cross-validation tests
 *
 * Copyright (C) 2026 Kerry Thompson
 * SPDX-License-Identifier: MIT
 *
 * Validates that TLV files built by the PC tool are decoded correctly by the
 * Amiga runtime.  Confirms uniform big-endian on-disk encoding round-trips
 * without corruption across block framing fields, token ID values, and
 * multi-pack types.
 *
 * Host:  make test-amiga-endian
 * Amiga: make TARGET=amiga test-amiga-endian  (build; run on device with STACK 100000)
 *
 * Exit code: 0 = all pass, non-zero = at least one failure.
 *
 * C89-compatible; vbcc-safe.
 *   - All variables declared at block start.
 *   - No // comments, no C99 types, no VLAs, no for-loop initialisers.
 *   - Only #include "whdtlv/whdtlv.h" -- no internal headers.
 *
 * See docs/tests/amiga-endian-crossval-plan.md for full rationale.
 */

#include "whdtlv/whdtlv.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/*------------------------------------------------------------------------*/
/* Test paths (relative to the repo root where make is invoked)          */

#define GAMES_TLV      "output/Game(2026-04-17).tlv"
#define MAGS_TLV       "output/Mags(2025-07-24).tlv"
#define DEFS_DIR       "assets_raw/defs"
#define PROFILE_PAL    "assets_raw/profiles/pal_aga_4mb.profile"
#define PROFILE_LEGACY "assets_raw/profiles/chipset_legacy_only.profile"
#define PROFILE_MULTI  "assets_raw/profiles/multi_bucket_reference.profile"

/*------------------------------------------------------------------------*/
/* Host baseline values captured during Phase 1 (2026-05-27)            */

#define HOST_GAME_VARIANTS  3973u
#define HOST_GAME_GROUPS    2904u
#define HOST_GAME_SELECTED  2904u
#define HOST_MULTI_LANES    4u
#define HOST_MAGS_GROUPS    103u

/*------------------------------------------------------------------------*/
/* Minimal test harness                                                   */

static int g_pass = 0;
static int g_fail = 0;

#define CHECK(cond, msg) \
    do { \
        if (cond) { \
            printf("  PASS: %s\n", msg); \
            g_pass++; \
        } else { \
            printf("  FAIL: %s\n", msg); \
            g_fail++; \
        } \
    } while (0)

static void print_sep(const char *name)
{
    printf("\n--- %s ---\n", name);
}

/*------------------------------------------------------------------------*/
/* T12 fixture: comparison helper                                         */

static int results_match_expected(
    const WhdTlvStringList *r,
    const char * const     *expected,
    unsigned int            expected_count)
{
    unsigned int i;

    if (r == NULL || expected == NULL) {
        return 0;
    }
    if (r->count != expected_count) {
        return 0;
    }
    for (i = 0u; i < expected_count; ++i) {
        if (r->items == NULL || r->items[i] == NULL || expected[i] == NULL) {
            return 0;
        }
        if (strcmp(r->items[i], expected[i]) != 0) {
            return 0;
        }
    }
    return 1;
}

/*------------------------------------------------------------------------*/
/* T12 fixture data                                                       */
/*
 * Fixture F01: AlienBreed2* under pal_aga_4mb.profile
 * Source: tests/filtering/expected/endian/f01_AlienBreed2_pal_aga_4mb.txt
 * Generated by host on 2026-05-27 from output/Game(2026-04-17).tlv
 * matched_groups=1 selected_variants=1 selection_lanes=1
 * Coverage: chipset token ID -- AGA winner selected
 */
static const char *f01_expected[] = {
    "AlienBreed2_v1.6_AGA_0044",
    NULL
};
static const unsigned int f01_count = 1u;

/*
 * Fixture F02: AlienBreed2* under chipset_legacy_only.profile
 * Source: tests/filtering/expected/endian/f02_AlienBreed2_chipset_legacy_only.txt
 * Generated by host on 2026-05-27 from output/Game(2026-04-17).tlv
 * matched_groups=1 selected_variants=1 selection_lanes=1
 * Coverage: second profile; same group, different chipset winner proves token ID decoding
 */
static const char *f02_expected[] = {
    "AlienBreed2_v1.6_0278",
    NULL
};
static const unsigned int f02_count = 1u;

/*
 * Fixture F03: lotus* under pal_aga_4mb.profile
 * Source: tests/filtering/expected/endian/f03_lotus_pal_aga_4mb.txt
 * Generated by host on 2026-05-27 from output/Game(2026-04-17).tlv
 * matched_groups=3 selected_variants=3 selection_lanes=1
 * Coverage: multi-group; token IDs decoded across three distinct groups
 */
static const char *f03_expected[] = {
    "Lotus2_v1.13_0497",
    "Lotus3_v1.6_0217",
    "Lotus_v1.1_0774",
    NULL
};
static const unsigned int f03_count = 3u;

/*
 * Fixture F04: body* under pal_aga_4mb.profile
 * Source: tests/filtering/expected/endian/f04_body_pal_aga_4mb.txt
 * Generated by host on 2026-05-27 from output/Game(2026-04-17).tlv
 * matched_groups=2 selected_variants=2 selection_lanes=1
 * Coverage: multi-group chipset diversity
 */
static const char *f04_expected[] = {
    "BodyBlows_v2.1_AGA_1322",
    "BodyBlowsGalactic_v2.2a_AGA_0440",
    NULL
};
static const unsigned int f04_count = 2u;

/*
 * Fixture F05: zool* under multi_bucket_reference.profile
 * Source: tests/filtering/expected/endian/f05_zool_multi_bucket.txt
 * Generated by host on 2026-05-27 from output/Game(2026-04-17).tlv
 * matched_groups=2 selected_variants=4 selection_lanes=4
 * Coverage: multi-lane; chipset x language bucket selection
 */
static const char *f05_expected[] = {
    "Zool2_v1.0_AGA_0415",
    "Zool2_v1.0_1111",
    "Zool_v2.0_AGA_1675",
    "Zool_v2.0_2426",
    NULL
};
static const unsigned int f05_count = 4u;

/* Fixture F06: no-match search -- expected array not used; zero count asserted directly */
/* zzznomatchzzz* under pal_aga_4mb.profile: matched_groups=0 selected_variants=0       */

/*========================================================================*/
/* T10 -- Group count matches host baseline                              */
/*========================================================================*/

static void test_T10_group_count(void)
{
    WhdTlvFilterOptions opts;
    WhdTlvFilterSummary summary;
    WhdTlvStringList    results;
    int                 rc;

    print_sep("T10: Group count matches host baseline (block 0x02 BE decoding)");

    whdtlv_filter_options_defaults(&opts);
    memset(&summary, 0, sizeof(summary));
    memset(&results, 0, sizeof(results));

    rc = whdtlv_filter_to_list(
        GAMES_TLV, DEFS_DIR, NULL,
        NULL, &opts, &results, &summary);

    CHECK(rc == WHDTLV_OK,
          "returns WHDTLV_OK");
    CHECK(summary.variants_total == HOST_GAME_VARIANTS,
          "variants_total == HOST_GAME_VARIANTS (3973)");
    CHECK(summary.groups_total == HOST_GAME_GROUPS,
          "groups_total == HOST_GAME_GROUPS (2904)");

    printf("  (variants=%u groups=%u)\n",
           summary.variants_total, summary.groups_total);

    whdtlv_string_list_free(&results);
}

/*========================================================================*/
/* T11 -- Selected variant count matches host baseline                   */
/*========================================================================*/

static void test_T11_selected_count(void)
{
    WhdTlvFilterOptions opts;
    WhdTlvFilterSummary summary;
    WhdTlvStringList    results;
    int                 rc;

    print_sep("T11: Selected variant count matches host baseline (token ID BE decoding)");

    whdtlv_filter_options_defaults(&opts);
    memset(&summary, 0, sizeof(summary));
    memset(&results, 0, sizeof(results));

    rc = whdtlv_filter_to_list(
        GAMES_TLV, DEFS_DIR, PROFILE_PAL,
        NULL, &opts, &results, &summary);

    CHECK(rc == WHDTLV_OK,
          "returns WHDTLV_OK");
    CHECK(summary.selected_variants == HOST_GAME_SELECTED,
          "selected_variants == HOST_GAME_SELECTED (2904)");
    CHECK(summary.selection_lanes == 1u,
          "selection_lanes == 1");

    printf("  (selected=%u lanes=%u)\n",
           summary.selected_variants, summary.selection_lanes);

    whdtlv_string_list_free(&results);
}

/*========================================================================*/
/* T12 -- Host-oracled fixture parity (6 sub-cases)                      */
/*========================================================================*/

static void test_T12_fixture_parity(void)
{
    WhdTlvFilterOptions opts;
    WhdTlvFilterSummary summary;
    WhdTlvStringList    results;
    int                 rc;
    int                 match;

    print_sep("T12: Host-oracled fixture parity");

    /*-- F01: AlienBreed2* + pal_aga_4mb -- AGA chipset winner --*/
    whdtlv_filter_options_defaults(&opts);
    memset(&summary, 0, sizeof(summary));
    memset(&results, 0, sizeof(results));

    rc = whdtlv_filter_to_list(
        GAMES_TLV, DEFS_DIR, PROFILE_PAL,
        "AlienBreed2*", &opts, &results, &summary);

    CHECK(rc == WHDTLV_OK,
          "F01: returns WHDTLV_OK");
    CHECK(results.count == f01_count,
          "F01: results.count == 1 (f01_count)");

    match = results_match_expected(&results, f01_expected, f01_count);
    CHECK(match,
          "F01: selected filenames match host oracle (AlienBreed2_v1.6_AGA_0044)");

    if (!match) {
        unsigned int i;
        printf("  F01 host expected: AlienBreed2_v1.6_AGA_0044\n");
        for (i = 0u; i < results.count; ++i) {
            printf("  F01 got[%u]: %s\n", i,
                   results.items[i] ? results.items[i] : "(NULL)");
        }
    }

    whdtlv_string_list_free(&results);

    /*-- F02: AlienBreed2* + chipset_legacy_only -- ECS/OCS winner --*/
    whdtlv_filter_options_defaults(&opts);
    memset(&summary, 0, sizeof(summary));
    memset(&results, 0, sizeof(results));

    rc = whdtlv_filter_to_list(
        GAMES_TLV, DEFS_DIR, PROFILE_LEGACY,
        "AlienBreed2*", &opts, &results, &summary);

    CHECK(rc == WHDTLV_OK,
          "F02: returns WHDTLV_OK");
    CHECK(results.count == f02_count,
          "F02: results.count == 1 (f02_count)");

    match = results_match_expected(&results, f02_expected, f02_count);
    CHECK(match,
          "F02: selected filenames match host oracle (AlienBreed2_v1.6_0278)");

    if (!match) {
        unsigned int i;
        printf("  F02 host expected: AlienBreed2_v1.6_0278\n");
        for (i = 0u; i < results.count; ++i) {
            printf("  F02 got[%u]: %s\n", i,
                   results.items[i] ? results.items[i] : "(NULL)");
        }
    }

    whdtlv_string_list_free(&results);

    /*-- F03: lotus* + pal_aga_4mb -- three groups --*/
    whdtlv_filter_options_defaults(&opts);
    memset(&summary, 0, sizeof(summary));
    memset(&results, 0, sizeof(results));

    rc = whdtlv_filter_to_list(
        GAMES_TLV, DEFS_DIR, PROFILE_PAL,
        "lotus*", &opts, &results, &summary);

    CHECK(rc == WHDTLV_OK,
          "F03: returns WHDTLV_OK");
    CHECK(results.count == f03_count,
          "F03: results.count == 3 (f03_count)");

    match = results_match_expected(&results, f03_expected, f03_count);
    CHECK(match,
          "F03: selected filenames match host oracle (Lotus2, Lotus3, Lotus)");

    if (!match) {
        unsigned int i;
        printf("  F03 host expected: Lotus2_v1.13_0497, Lotus3_v1.6_0217, Lotus_v1.1_0774\n");
        for (i = 0u; i < results.count; ++i) {
            printf("  F03 got[%u]: %s\n", i,
                   results.items[i] ? results.items[i] : "(NULL)");
        }
    }

    whdtlv_string_list_free(&results);

    /*-- F04: body* + pal_aga_4mb -- two groups, AGA winners --*/
    whdtlv_filter_options_defaults(&opts);
    memset(&summary, 0, sizeof(summary));
    memset(&results, 0, sizeof(results));

    rc = whdtlv_filter_to_list(
        GAMES_TLV, DEFS_DIR, PROFILE_PAL,
        "body*", &opts, &results, &summary);

    CHECK(rc == WHDTLV_OK,
          "F04: returns WHDTLV_OK");
    CHECK(results.count == f04_count,
          "F04: results.count == 2 (f04_count)");

    match = results_match_expected(&results, f04_expected, f04_count);
    CHECK(match,
          "F04: selected filenames match host oracle (BodyBlows, BodyBlowsGalactic)");

    if (!match) {
        unsigned int i;
        printf("  F04 host expected: BodyBlows_v2.1_AGA_1322, BodyBlowsGalactic_v2.2a_AGA_0440\n");
        for (i = 0u; i < results.count; ++i) {
            printf("  F04 got[%u]: %s\n", i,
                   results.items[i] ? results.items[i] : "(NULL)");
        }
    }

    whdtlv_string_list_free(&results);

    /*-- F05: zool* + multi_bucket_reference -- 4 results, 4 lanes --*/
    whdtlv_filter_options_defaults(&opts);
    memset(&summary, 0, sizeof(summary));
    memset(&results, 0, sizeof(results));

    rc = whdtlv_filter_to_list(
        GAMES_TLV, DEFS_DIR, PROFILE_MULTI,
        "zool*", &opts, &results, &summary);

    CHECK(rc == WHDTLV_OK,
          "F05: returns WHDTLV_OK");
    CHECK(summary.selection_lanes == 4u,
          "F05: selection_lanes == 4 (multi-lane)");
    CHECK(results.count == f05_count,
          "F05: results.count == 4 (f05_count)");

    match = results_match_expected(&results, f05_expected, f05_count);
    CHECK(match,
          "F05: selected filenames match host oracle (Zool2 AGA, Zool2, Zool AGA, Zool)");

    if (!match) {
        unsigned int i;
        printf("  F05 host expected: Zool2_v1.0_AGA_0415, Zool2_v1.0_1111, Zool_v2.0_AGA_1675, Zool_v2.0_2426\n");
        for (i = 0u; i < results.count; ++i) {
            printf("  F05 got[%u]: %s\n", i,
                   results.items[i] ? results.items[i] : "(NULL)");
        }
    }

    whdtlv_string_list_free(&results);

    /*-- F06: zzznomatchzzz* + pal_aga_4mb -- no match --*/
    whdtlv_filter_options_defaults(&opts);
    memset(&summary, 0, sizeof(summary));
    memset(&results, 0, sizeof(results));

    rc = whdtlv_filter_to_list(
        GAMES_TLV, DEFS_DIR, PROFILE_PAL,
        "zzznomatchzzz*", &opts, &results, &summary);

    CHECK(rc == WHDTLV_OK,
          "F06: returns WHDTLV_OK");
    CHECK(results.count == 0u,
          "F06: results.count == 0");
    CHECK(summary.matched_groups == 0u,
          "F06: matched_groups == 0");

    printf("  F06 (matched_groups=%u selected=%u)\n",
           summary.matched_groups, results.count);

    whdtlv_string_list_free(&results);
}

/*========================================================================*/
/* T13 -- CRC fingerprint validation passes                              */
/*========================================================================*/

static void test_T13_crc_validation(void)
{
    WhdTlvFilterOptions opts;
    WhdTlvFilterSummary summary;
    WhdTlvStringList    results;
    int                 rc;

    print_sep("T13: CRC fingerprint validation passes (block 0x04 BE uint32 decoding)");

    whdtlv_filter_options_defaults(&opts);
    memset(&summary, 0, sizeof(summary));
    memset(&results, 0, sizeof(results));

    rc = whdtlv_filter_to_list(
        GAMES_TLV, DEFS_DIR, PROFILE_PAL,
        NULL, &opts, &results, &summary);

    CHECK(rc == WHDTLV_OK,
          "returns WHDTLV_OK (ERR_CRC=-5 would appear here)");
    CHECK(summary.crc_mismatches == 0u,
          "crc_mismatches == 0");
    CHECK(summary.crc_files_checked > 0u,
          "crc_files_checked > 0 (CRC path was exercised)");

    printf("  (crc_files_checked=%u crc_mismatches=%u)\n",
           summary.crc_files_checked, summary.crc_mismatches);

    whdtlv_string_list_free(&results);
}

/*========================================================================*/
/* T14 -- Mags pack type loads with correct group count                  */
/*========================================================================*/

static void test_T14_mags_group_count(void)
{
    WhdTlvFilterOptions opts;
    WhdTlvFilterSummary summary;
    WhdTlvStringList    results;
    int                 rc;

    print_sep("T14: Mags pack type loads with correct group count (multi-pack block framing)");

    whdtlv_filter_options_defaults(&opts);
    memset(&summary, 0, sizeof(summary));
    memset(&results, 0, sizeof(results));

    rc = whdtlv_filter_to_list(
        MAGS_TLV, DEFS_DIR, NULL,
        NULL, &opts, &results, &summary);

    CHECK(rc == WHDTLV_OK,
          "returns WHDTLV_OK");
    CHECK(summary.groups_total == HOST_MAGS_GROUPS,
          "groups_total == HOST_MAGS_GROUPS (103)");

    printf("  (groups_total=%u)\n", summary.groups_total);

    whdtlv_string_list_free(&results);
}

/*========================================================================*/
/* T15 -- Multi-lane profile produces correct lane count                 */
/*========================================================================*/

static void test_T15_multi_lane(void)
{
    WhdTlvFilterOptions opts;
    WhdTlvFilterSummary summary;
    WhdTlvStringList    results;
    int                 rc;

    print_sep("T15: Multi-lane profile produces correct lane count (token ID lane routing)");

    whdtlv_filter_options_defaults(&opts);
    memset(&summary, 0, sizeof(summary));
    memset(&results, 0, sizeof(results));

    rc = whdtlv_filter_to_list(
        GAMES_TLV, DEFS_DIR, PROFILE_MULTI,
        NULL, &opts, &results, &summary);

    CHECK(rc == WHDTLV_OK,
          "returns WHDTLV_OK");
    CHECK(summary.selection_lanes == HOST_MULTI_LANES,
          "selection_lanes == HOST_MULTI_LANES (4)");
    CHECK(results.count == summary.selected_variants,
          "results.count == selected_variants (list length matches summary)");
    CHECK(summary.selected_variants > 0u,
          "selected_variants > 0");

    printf("  (lanes=%u selected=%u)\n",
           summary.selection_lanes, summary.selected_variants);

    whdtlv_string_list_free(&results);
}

/*========================================================================*/
/* main                                                                   */
/*========================================================================*/

int main(void)
{
    printf("whdtlv Amiga endianness cross-validation test suite\n");
    printf("Games TLV : %s\n", GAMES_TLV);
    printf("Mags TLV  : %s\n", MAGS_TLV);
    printf("Defs      : %s\n", DEFS_DIR);
    printf("Baselines : variants=%u groups=%u selected=%u mags_groups=%u multi_lanes=%u\n",
           HOST_GAME_VARIANTS, HOST_GAME_GROUPS, HOST_GAME_SELECTED,
           HOST_MAGS_GROUPS, HOST_MULTI_LANES);

    test_T10_group_count();
    test_T11_selected_count();
    test_T12_fixture_parity();
    test_T13_crc_validation();
    test_T14_mags_group_count();
    test_T15_multi_lane();

    printf("\n========================================\n");
    printf("Results: %d passed, %d failed\n", g_pass, g_fail);
    printf("========================================\n");

    return (g_fail == 0) ? 0 : 1;
}

/* End of Text */
